"""
Dash Design Kit theme configuration
"""
theme = {
    "accent": "#E75224",
    "accent_positive": "#70B562",
    "accent_negative": "#C63E32",
    "background_content": "#F5F5F5",
    "background_page": "#FFFFFF",
    "body_text": "#2c3e50",
    "border": "#D6D6D6",
    "border_style": {
        "name": "underlined",
        "borderWidth": "0px 0px 0px 0px",
        "borderStyle": "solid",
        "borderRadius": 0,
    },
    "button_border": {"width": "1px", "color": "#E75224", "radius": "0px"},
    "button_capitalization": "none",
    "button_text": "#FFFFFF",
    "button_background_color": "#E75224",
    "control_border": {
        "width": "1px 1px 1px 1px",
        "color": "#BFC0C2",
        "radius": "0px",
    },
    "control_background_color": "#F8FAFC",
    "control_text": "#131925",
    "card_margin": "20px",
    "card_padding": "8px",
    "card_border": {
        "width": "0px",
        "style": "solid",
        "color": "#F0F0F0",
        "radius": "0px",
    },
    "card_background_color": "#F0F0F0",
    "card_box_shadow": "0px 0px 5px rgba(0,0,0,0)",
    "card_outline": {"width": "0px", "style": "solid", "color": "#F0F0F0"},
    "card_header_accent": "#D4D7DE",
    "card_header_margin": "0px 0px 16px 0px",
    "card_header_padding": "12px",
    "card_header_border": {
        "width": "0px 0px 0px 0px",
        "style": "solid",
        "color": "#62A6FB",
        "radius": "0px",
    },
    "card_header_background_color": "#F0F0F0",
    "card_title_text": "#131925",
    "card_title_font_size": "20px",
    "card_description_background_color": "#F0F0F0",
    "card_description_text": "#131925",
    "card_menu_background_color": "#FFF",
    "card_menu_text": "#101010",
    "card_header_box_shadow": "0px 0px 0px rgba(0,0,0,0)",
    "card_accent": "#828282",
    "breakpoint_font": "700px",
    "breakpoint_stack_blocks": "700px",
    "colorway": [
        "#0075a8",
        "#99c8dc",
        "#bf5227",
        "#d9977d",
        "#595959",
        "#a6a6a6",
        "#1b365d",
        "#7986cb",
        "#00948f",
        "#a15f45",
    ],
    "colorscale": [
        "#f2b9a3",
        "#edaa91",
        "#e79b81",
        "#e08c70",
        "#da7d60",
        "#d36d51",
        "#cc5e42",
        "#c44d34",
        "#bc3b26",
        "#b42519",
    ],
    "dbc_primary": "#E75224",
    "dbc_secondary": "#5FA7C6",
    "dbc_info": "#4758C2",
    "dbc_gray": "#828282",
    "dbc_success": "#70B562",
    "dbc_warning": "#EBAD2A",
    "dbc_danger": "#C63E32",
    "font_family": "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    "font_family_header": "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    "font_family_headings": "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    "font_size": "16px",
    "font_size_smaller_screen": "16px",
    "font_size_header": "24px",
    "footer_background_color": "#1a1a1a",
    "footer_title_text": "#FFFFFF",
    "footer_title_font_size": "24px",
    "title_capitalization": "none",
    "header_content_alignment": "spread",
    "header_margin": "0px 0px 24px 0px",
    "header_padding": "0px 16px 0px 0px",
    "header_border": {
        "width": "0px 0px 0px 0px",
        "style": "solid",
        "color": "#828282",
        "radius": "0px",
    },
    "header_background_color": "#1b365d",
    "header_box_shadow": "0px 1px 3px rgba(0,0,0,0)",
    "header_text": "#FFFFFF",
    "heading_text": "#131925",
    "hero_background_color": "#636873",
    "hero_title_text": "#FFFFFF",
    "hero_subtitle_text": "#F9F9F9",
    "hero_controls_background_color": "rgba(215, 215, 215, 0.9)",
    "hero_controls_label_text": "#131925",
    "hero_controls_label_font_size": "14px",
    "hero_controls_grid_columns": 4,
    "hero_controls_accent": "#0075a8",
    "hero_border": {"width": "0", "style": "solid", "color": "transparent"},
    "hero_padding": "24px",
    "hero_gap": "24px",
    "text": "#131925",
    "report_background": "#f0f0f0",
    "report_background_content": "whitesmoke",
    "report_background_page": "white",
    "report_text": "black",
    "report_font_family": "Inter, sans-serif",
    "report_font_size": "12px",
    "section_padding": "24px",
    "section_title_font_size": "24px",
    "section_gap": "24px",
    "report_border": "#D6D6D6",
    "graph_grid_color": "#CCCCCC",
    "table_striped_even": "#FFFFFF",
    "table_striped_odd": "#FFFFFF",
    "table_border": "#000000",
    "tag_background_color": "#FFFFFF",
    "tag_text": "#131925",
    "tag_font_size": "14px",
    "tag_border": {
        "width": "0px",
        "style": "solid",
        "color": "#F1F2F4",
        "radius": "0px",
    },
    "tooltip_background_color": "#253247",
    "tooltip_text": "#FFF",
    "tooltip_font_size": "14px",
    "top_control_panel_border": {
        "width": "1px",
        "style": "solid",
        "color": "#F0F0F0",
    },
    "color_scheme": "light",
    "card_description_font_size": "16px",
    "header_controls_background_color": "#F1F1F1",
    "hero_title_font_size": "48px",
    "hero_subtitle_font_size": "16px",
}

